cors:
  allowed-origins:
    - *
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

---

# Production profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://machim.go.ro:56432/mydb
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cors:
    allowed-origins:
      - https://d24eqtkw4p9swm.cloudfront.net
