name: Deploy
on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write         # REQUIRED for OIDC
  contents: read          # to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::048643934642:role/GitHubActions-ECR-Push
          aws-region: us-east-1

      # (Optional) Verify identity
      - name: Who am I?
        run: aws sts get-caller-identity

      # Example: login to ECR and push an image
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push image
        env:
          AWS_ACCOUNT_ID: 048643934642
          AWS_REGION: us-east-1
        run: |
          docker buildx build -t 048643934642.dkr.ecr.us-east-1.amazonaws.com/proptech:latest-amd64  --push .
