name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Who am I?
      with:
        aws-region: us-east-1
        command: aws sts get-caller-identity
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::048643934642:role/GitHubActions-ECR-Push
        aws-region: us-east-1
    - name: Build the Docker image
      run: docker buildx build -t 048643934642.dkr.ecr.us-east-1.amazonaws.com/proptech:latest-amd64  --push .
